export const rules = {
  alignContent: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
    stretch: 'stretch',
    baseline: 'baseline',
  },
  alignItems: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
    stretch: 'stretch',
    baseline: 'baseline',
  },
  alignSelf: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
    stretch: 'stretch',
    baseline: 'baseline',
  },
  backgroundPositionX: {
    left: 'left',
    center: 'center',
    right: 'right',
  },
  backgroundPositionY: {
    top: 'top',
    center: 'center',
    bottom: 'bottom',
  },
  backgroundRepeat: {
    repeat: 'repeat',
    'repeat-x': 'repeat-x',
    'repeat-y': 'repeat-y',
    'no-repeat': 'no-repeat',
  },
  backgroundSize: {
    cover: 'cover',
    contain: 'contain',
  },
  borderRadius: {
    none: 0,
  },
  borderStyle: {
    none: 'none',
    solid: 'solid',
    dotted: 'dotted',
    dashed: 'dashed',
  },
  borderWidth: {
    none: 0,
    '1px': '1px',
  },
  bottom: {
    auto: 'auto',
    0: 0,
  },
  cursor: {
    auto: 'auto',
    default: 'default',
    pointer: 'pointer',
    wait: 'wait',
    text: 'text',
    move: 'move',
    notAllowed: 'not-allowed',
  },
  display: {
    none: 'none',
    inline: 'inline',
    block: 'block',
    inlineBlock: 'inline-block',
    flex: 'flex',
    inlineFlex: 'inline-flex',
    grid: 'grid',
    inlineGrid: 'inline-grid',
    listItem: 'list-item',
  },
  flex: {
    equal0: '1 1 0px',
  },
  flexBasis: {
    auto: 'auto',
    full: '100%',
    0: '0px',
    '1/12': `${(1 / 12) * 100}%`,
    '2/12': `${(2 / 12) * 100}%`,
    '3/12': `${(3 / 12) * 100}%`,
    '4/12': `${(4 / 12) * 100}%`,
    '5/12': `${(5 / 12) * 100}%`,
    '6/12': `${(6 / 12) * 100}%`,
    '7/12': `${(7 / 12) * 100}%`,
    '8/12': `${(8 / 12) * 100}%`,
    '9/12': `${(9 / 12) * 100}%`,
    '10/12': `${(10 / 12) * 100}%`,
    '11/12': `${(11 / 12) * 100}%`,
  },
  flexDirection: {
    row: 'row',
    rowReverse: 'row-reverse',
    column: 'column',
    columnReverse: 'column-reverse',
  },
  flexGrow: {
    0: 0,
    1: 1,
  },
  flexShrink: {
    0: 0,
    1: 1,
  },
  flexWrap: {
    wrap: 'wrap',
    nowrap: 'nowrap',
  },
  fontStyle: {
    normal: 'normal',
    italic: 'italic',
  },
  fontWeight: {
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    heavy: 800,
    black: 900,
  },
  gridAutoFlow: {
    row: 'row',
    rowDense: 'row dense',
    column: 'column',
    columnDense: 'column dense',
  },
  gridColumn: {
    auto: 'auto',
    'span-1': 'span 1 / span 1',
    'span-2': 'span 2 / span 2',
    'span-3': 'span 3 / span 3',
    'span-4': 'span 4 / span 4',
    'span-5': 'span 5 / span 5',
    'span-6': 'span 6 / span 6',
    'span-7': 'span 7 / span 7',
    'span-8': 'span 8 / span 8',
    'span-9': 'span 9 / span 9',
    'span-10': 'span 10 / span 10',
    'span-11': 'span 11 / span 11',
    'span-12': 'span 12 / span 12',
  },
  gridRow: {
    auto: 'auto',
    'span-1': 'span 1 / span 1',
    'span-2': 'span 2 / span 2',
    'span-3': 'span 3 / span 3',
    'span-4': 'span 4 / span 4',
    'span-5': 'span 5 / span 5',
    'span-6': 'span 6 / span 6',
  },
  gridTemplateColumns: {
    1: 'repeat(1, minmax(0, 1fr))',
    2: 'repeat(2, minmax(0, 1fr))',
    3: 'repeat(3, minmax(0, 1fr))',
    4: 'repeat(4, minmax(0, 1fr))',
    5: 'repeat(5, minmax(0, 1fr))',
    6: 'repeat(6, minmax(0, 1fr))',
    7: 'repeat(7, minmax(0, 1fr))',
    8: 'repeat(8, minmax(0, 1fr))',
    9: 'repeat(9, minmax(0, 1fr))',
    10: 'repeat(10, minmax(0, 1fr))',
    11: 'repeat(11, minmax(0, 1fr))',
    12: 'repeat(12, minmax(0, 1fr))',
    none: 'none',
  },
  gridTemplateRows: {
    1: 'repeat(1, minmax(0, 1fr))',
    2: 'repeat(2, minmax(0, 1fr))',
    3: 'repeat(3, minmax(0, 1fr))',
    4: 'repeat(4, minmax(0, 1fr))',
    5: 'repeat(5, minmax(0, 1fr))',
    6: 'repeat(6, minmax(0, 1fr))',
    none: 'none',
  },
  height: {
    auto: 'auto',
    full: '100%',
    '1px': '1px',
  },
  justifyContent: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
    spaceBetween: 'space-between',
  },
  justifyItems: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
  },
  justifySelf: {
    center: 'center',
    start: 'flex-start',
    end: 'flex-end',
  },
  left: {
    auto: 'auto',
    0: 0,
  },
  letterSpacing: {
    normal: 'normal',
    none: 0,
  },
  listStyle: {
    none: 'none',
    disc: 'disc',
    decimal: 'decimal',
  },
  opacity: {
    0: 0,
    25: 0.25,
    50: 0.5,
    75: 0.75,
    100: 1,
  },
  outline: {
    none: 'none',
  },
  overflow: {
    auto: 'auto',
    hidden: 'hidden',
    scroll: 'scroll',
  },
  overflowX: {
    auto: 'auto',
    hidden: 'hidden',
    scroll: 'scroll',
  },
  overflowY: {
    auto: 'auto',
    hidden: 'hidden',
    scroll: 'scroll',
  },
  pointerEvents: {
    none: 'none',
    auto: 'auto',
  },
  position: {
    static: 'static',
    relative: 'relative',
    absolute: 'absolute',
    fixed: 'fixed',
    sticky: 'sticky',
  },
  right: {
    auto: 'auto',
    0: 0,
  },
  textAlign: {
    left: 'left',
    center: 'center',
    right: 'right',
  },
  textTransform: {
    uppercase: 'uppercase',
    lowercase: 'lowercase',
    capitalize: 'capitalize',
  },
  top: {
    auto: 'auto',
    0: 0,
  },
  transitionTimingFunction: {
    linear: 'linear',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1);',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1);',
    easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1);',
  },
  userSelect: {
    none: 'none',
  },
  width: {
    auto: 'auto',
    full: '100%',
    '1px': '1px',
    '1/12': `${(1 / 12) * 100}%`,
    '2/12': `${(2 / 12) * 100}%`,
    '3/12': `${(3 / 12) * 100}%`,
    '4/12': `${(4 / 12) * 100}%`,
    '5/12': `${(5 / 12) * 100}%`,
    '6/12': `${(6 / 12) * 100}%`,
    '7/12': `${(7 / 12) * 100}%`,
    '8/12': `${(8 / 12) * 100}%`,
    '9/12': `${(9 / 12) * 100}%`,
    '10/12': `${(10 / 12) * 100}%`,
    '11/12': `${(11 / 12) * 100}%`,
  },
  zIndex: {
    auto: 'auto',
    [-1]: -1,
    0: 1,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
  },
} as const
